import 'package:flutter/material.dart';

import '../models/letter_sound_models.dart';

const List<LetterSoundStage> letterSoundStages = [
  LetterSoundStage(
    code: 'A-C',
    title: 'A-C Sound Party',
    subtitle: '先听声音，再看图，再勇敢开口跟读。',
    chinesePrompt: '这一关有A、B、C。先点大卡片听发音，再玩听音找字母和找图片。',
    primaryColor: Color(0xFFFFD180),
    secondaryColor: Color(0xFFFF8A65),
    items: [
      LetterSoundItem(
        letter: 'A',
        phonicsText: '/a/',
        soundCue: 'A says a.',
        primaryWord: 'ant',
        secondaryWord: 'apple',
        primaryEmoji: '🐜',
        secondaryEmoji: '🍎',
        chinesePrompt: 'A张大嘴，像小蚂蚁在打招呼。先听a，再听ant和apple。',
        chant: 'A, a, a. Ant and apple.',
        accentColor: Color(0xFFFFB74D),
      ),
      LetterSoundItem(
        letter: 'B',
        phonicsText: '/b/',
        soundCue: 'B says b.',
        primaryWord: 'bird',
        secondaryWord: 'banana',
        primaryEmoji: '🐦',
        secondaryEmoji: '🍌',
        chinesePrompt: 'B先把小嘴巴闭起来，再轻轻蹦出b的声音。',
        chant: 'B, b, b. Bird and banana.',
        accentColor: Color(0xFFBA68C8),
      ),
      LetterSoundItem(
        letter: 'C',
        phonicsText: '/k/',
        soundCue: 'C says k.',
        primaryWord: 'cat',
        secondaryWord: 'cake',
        primaryEmoji: '🐱',
        secondaryEmoji: '🍰',
        chinesePrompt: '这里的C像小猫轻轻咔一声，听起来像k。',
        chant: 'C, c, c. Cat and cake.',
        accentColor: Color(0xFF4DB6AC),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'D-F',
    title: 'D-F Drum Beat',
    subtitle: '会敲鼓、会吹风、会微笑的大声音都在这里。',
    chinesePrompt: '这一关有D、E、F。可以先听卡片，再试试哪一个字母和单词是一家人。',
    primaryColor: Color(0xFFA5D6A7),
    secondaryColor: Color(0xFF66BB6A),
    items: [
      LetterSoundItem(
        letter: 'D',
        phonicsText: '/d/',
        soundCue: 'D says d.',
        primaryWord: 'dog',
        secondaryWord: 'desk',
        primaryEmoji: '🐶',
        secondaryEmoji: '🪑',
        chinesePrompt: 'D像轻轻敲小鼓，舌尖点一下，上面就出来d。',
        chant: 'D, d, d. Dog and desk.',
        accentColor: Color(0xFF81C784),
      ),
      LetterSoundItem(
        letter: 'E',
        phonicsText: '/e/',
        soundCue: 'E says e.',
        primaryWord: 'egg',
        secondaryWord: 'elephant',
        primaryEmoji: '🥚',
        secondaryEmoji: '🐘',
        chinesePrompt: 'E轻轻笑一笑，像看到大象时说eh。',
        chant: 'E, e, e. Egg and elephant.',
        accentColor: Color(0xFFFFD54F),
      ),
      LetterSoundItem(
        letter: 'F',
        phonicsText: '/f/',
        soundCue: 'F says f.',
        primaryWord: 'fish',
        secondaryWord: 'flower',
        primaryEmoji: '🐟',
        secondaryEmoji: '🌼',
        chinesePrompt: 'F像吹羽毛，上牙轻轻碰下唇，风就吹出来了。',
        chant: 'F, f, f. Fish and flower.',
        accentColor: Color(0xFF4FC3F7),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'G-I',
    title: 'G-I Adventure',
    subtitle: '山羊、小马和小墨水一起带我们找声音。',
    chinesePrompt: '这一关有G、H、I。先听开头声音，再看看哪张图和它最像。',
    primaryColor: Color(0xFF90CAF9),
    secondaryColor: Color(0xFF42A5F5),
    items: [
      LetterSoundItem(
        letter: 'G',
        phonicsText: '/g/',
        soundCue: 'G says g.',
        primaryWord: 'girl',
        secondaryWord: 'goat',
        primaryEmoji: '👧',
        secondaryEmoji: '🐐',
        chinesePrompt: 'G从嘴巴后面滚出来，像山羊goat开头的g。',
        chant: 'G, g, g. Girl and goat.',
        accentColor: Color(0xFF64B5F6),
      ),
      LetterSoundItem(
        letter: 'H',
        phonicsText: '/h/',
        soundCue: 'H says h.',
        primaryWord: 'hat',
        secondaryWord: 'horse',
        primaryEmoji: '🎩',
        secondaryEmoji: '🐴',
        chinesePrompt: 'H像对着镜子哈一口气，轻轻把气送出来。',
        chant: 'H, h, h. Hat and horse.',
        accentColor: Color(0xFFFFB74D),
      ),
      LetterSoundItem(
        letter: 'I',
        phonicsText: '/i/',
        soundCue: 'I says i.',
        primaryWord: 'ink',
        secondaryWord: 'insect',
        primaryEmoji: '🖋️',
        secondaryEmoji: '🐞',
        chinesePrompt: 'I短短地响一下，像小墨水滴答一下。',
        chant: 'I, i, i. Ink and insect.',
        accentColor: Color(0xFFF06292),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'J-L',
    title: 'J-L Jungle Ride',
    subtitle: '果汁、风筝和小狮子，带着声音往前跑。',
    chinesePrompt: '这一关有J、K、L。卡片里有两个例词，点小图片也能单独听声音。',
    primaryColor: Color(0xFFFFCC80),
    secondaryColor: Color(0xFFFFA726),
    items: [
      LetterSoundItem(
        letter: 'J',
        phonicsText: '/j/',
        soundCue: 'J says j.',
        primaryWord: 'juice',
        secondaryWord: 'jellyfish',
        primaryEmoji: '🧃',
        secondaryEmoji: '🪼',
        chinesePrompt: 'J像果汁跳出来，先轻轻挡住，再放开声音。',
        chant: 'J, j, j. Juice and jellyfish.',
        accentColor: Color(0xFFFFA726),
      ),
      LetterSoundItem(
        letter: 'K',
        phonicsText: '/k/',
        soundCue: 'K says k.',
        primaryWord: 'kite',
        secondaryWord: 'kangaroo',
        primaryEmoji: '🪁',
        secondaryEmoji: '🦘',
        chinesePrompt: 'K从嘴巴后面轻轻弹出来，像风筝飞起时的小风。',
        chant: 'K, k, k. Kite and kangaroo.',
        accentColor: Color(0xFF26C6DA),
      ),
      LetterSoundItem(
        letter: 'L',
        phonicsText: '/l/',
        soundCue: 'L says l.',
        primaryWord: 'lion',
        secondaryWord: 'lemon',
        primaryEmoji: '🦁',
        secondaryEmoji: '🍋',
        chinesePrompt: 'L舌尖轻轻碰上面，像小狮子亮相时发出的l。',
        chant: 'L, l, l. Lion and lemon.',
        accentColor: Color(0xFFFFEE58),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'M-O',
    title: 'M-O Moon Garden',
    subtitle: '用鼻子哼、用嘴巴圆，一起把声音种出来。',
    chinesePrompt: '这一关有M、N、O。可以一边听一边看图，再玩小游戏巩固。',
    primaryColor: Color(0xFFCE93D8),
    secondaryColor: Color(0xFFAB47BC),
    items: [
      LetterSoundItem(
        letter: 'M',
        phonicsText: '/m/',
        soundCue: 'M says m.',
        primaryWord: 'monkey',
        secondaryWord: 'milk',
        primaryEmoji: '🐵',
        secondaryEmoji: '🥛',
        chinesePrompt: 'M把嘴巴轻轻闭起来，用鼻子哼一声就出来了。',
        chant: 'M, m, m. Monkey and milk.',
        accentColor: Color(0xFFBA68C8),
      ),
      LetterSoundItem(
        letter: 'N',
        phonicsText: '/n/',
        soundCue: 'N says n.',
        primaryWord: 'nose',
        secondaryWord: 'nurse',
        primaryEmoji: '👃',
        secondaryEmoji: '🧑‍⚕️',
        chinesePrompt: 'N舌尖碰一下上面，鼻子帮忙，让声音轻轻出来。',
        chant: 'N, n, n. Nose and nurse.',
        accentColor: Color(0xFF7986CB),
      ),
      LetterSoundItem(
        letter: 'O',
        phonicsText: '/o/',
        soundCue: 'O says o.',
        primaryWord: 'ox',
        secondaryWord: 'orange',
        primaryEmoji: '🐂',
        secondaryEmoji: '🍊',
        chinesePrompt: 'O把嘴巴圆圆地张开，像看到橙子时说o。',
        chant: 'O, o, o. Ox and orange.',
        accentColor: Color(0xFFFF8A65),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'P-R',
    title: 'P-R Rocket Town',
    subtitle: '爆米花、问题和小兔子，把声音送上天空。',
    chinesePrompt: '这一关有P、Q、R。先听，再点，再答题，慢慢就会更熟。',
    primaryColor: Color(0xFFFFAB91),
    secondaryColor: Color(0xFFFF7043),
    items: [
      LetterSoundItem(
        letter: 'P',
        phonicsText: '/p/',
        soundCue: 'P says p.',
        primaryWord: 'pizza',
        secondaryWord: 'panda',
        primaryEmoji: '🍕',
        secondaryEmoji: '🐼',
        chinesePrompt: 'P像爆米花噗一下，双唇一弹，声音就出来了。',
        chant: 'P, p, p. Pizza and panda.',
        accentColor: Color(0xFFFF8A65),
      ),
      LetterSoundItem(
        letter: 'Q',
        phonicsText: '/kw/',
        soundCue: 'Q says kw.',
        primaryWord: 'queen',
        secondaryWord: 'question',
        primaryEmoji: '👑',
        secondaryEmoji: '❓',
        chinesePrompt: 'Q常常和u一起走，像quick quick那样往前跳。',
        chant: 'Q, q, q. Queen and question.',
        accentColor: Color(0xFF9575CD),
      ),
      LetterSoundItem(
        letter: 'R',
        phonicsText: '/r/',
        soundCue: 'R says r.',
        primaryWord: 'rabbit',
        secondaryWord: 'robot',
        primaryEmoji: '🐰',
        secondaryEmoji: '🤖',
        chinesePrompt: 'R嘴巴微微圆起来，像小兔子快跑时的r。',
        chant: 'R, r, r. Rabbit and robot.',
        accentColor: Color(0xFF4DD0E1),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'S-U',
    title: 'S-U Sunny Trail',
    subtitle: '小蛇、老虎和雨伞，一起把声音走明白。',
    chinesePrompt: '这一关有S、T、U。听完可以马上挑战小游戏，看看自己记住没有。',
    primaryColor: Color(0xFFFFF59D),
    secondaryColor: Color(0xFFFFD54F),
    items: [
      LetterSoundItem(
        letter: 'S',
        phonicsText: '/s/',
        soundCue: 'S says s.',
        primaryWord: 'snake',
        secondaryWord: 'spider',
        primaryEmoji: '🐍',
        secondaryEmoji: '🕷️',
        chinesePrompt: 'S像小蛇嘶嘶滑过去，牙齿靠近，风从中间出来。',
        chant: 'S, s, s. Snake and spider.',
        accentColor: Color(0xFFFFD54F),
      ),
      LetterSoundItem(
        letter: 'T',
        phonicsText: '/t/',
        soundCue: 'T says t.',
        primaryWord: 'tiger',
        secondaryWord: 'tomato',
        primaryEmoji: '🐯',
        secondaryEmoji: '🍅',
        chinesePrompt: 'T像轻轻敲一下桌子，舌尖一点就弹出来了。',
        chant: 'T, t, t. Tiger and tomato.',
        accentColor: Color(0xFFFF8A65),
      ),
      LetterSoundItem(
        letter: 'U',
        phonicsText: '/u/',
        soundCue: 'U says u.',
        primaryWord: 'umbrella',
        secondaryWord: 'uncle',
        primaryEmoji: '☂️',
        secondaryEmoji: '🧔',
        chinesePrompt: 'U像雨伞打开一样，嘴巴轻轻松松发出u。',
        chant: 'U, u, u. Umbrella and uncle.',
        accentColor: Color(0xFF4FC3F7),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'V-X',
    title: 'V-X Wonder Walk',
    subtitle: '会震动的v、会圆嘴的w，还有藏在尾巴里的x。',
    chinesePrompt: '这一关有V、W、X。X比较特别，常常藏在单词后面，听的时候要留神。',
    primaryColor: Color(0xFF80DEEA),
    secondaryColor: Color(0xFF26C6DA),
    items: [
      LetterSoundItem(
        letter: 'V',
        phonicsText: '/v/',
        soundCue: 'V says v.',
        primaryWord: 'van',
        secondaryWord: 'vase',
        primaryEmoji: '🚐',
        secondaryEmoji: '🏺',
        chinesePrompt: 'V和f很像，可是喉咙会轻轻震动，像小车开过来。',
        chant: 'V, v, v. Van and vase.',
        accentColor: Color(0xFF26C6DA),
      ),
      LetterSoundItem(
        letter: 'W',
        phonicsText: '/w/',
        soundCue: 'W says w.',
        primaryWord: 'watch',
        secondaryWord: 'worm',
        primaryEmoji: '⌚',
        secondaryEmoji: '🪱',
        chinesePrompt: 'W先把嘴巴圆起来，再轻轻滑开，像wind吹过去。',
        chant: 'W, w, w. Watch and worm.',
        accentColor: Color(0xFF42A5F5),
      ),
      LetterSoundItem(
        letter: 'X',
        phonicsText: '/ks/',
        soundCue: 'X says ks.',
        primaryWord: 'box',
        secondaryWord: 'fox',
        primaryEmoji: '📦',
        secondaryEmoji: '🦊',
        chinesePrompt: 'X像box尾巴里的ks，两个小声音手拉手出来。',
        chant: 'X, x, x. Box and fox.',
        accentColor: Color(0xFFEF5350),
      ),
    ],
  ),
  LetterSoundStage(
    code: 'Y-Z',
    title: 'Y-Z Yay Finish',
    subtitle: '最后两位好朋友，学完就能完成一整圈字母发音旅行。',
    chinesePrompt: '最后一关有Y和Z。学完这一关，就把整套字母自然拼读走完啦。',
    primaryColor: Color(0xFFB39DDB),
    secondaryColor: Color(0xFF7E57C2),
    items: [
      LetterSoundItem(
        letter: 'Y',
        phonicsText: '/y/',
        soundCue: 'Y says y.',
        primaryWord: 'yo-yo',
        secondaryWord: 'yak',
        primaryEmoji: '🪀',
        secondaryEmoji: '🐂',
        chinesePrompt: 'Y像yes开头那样轻快地滑出来，声音短短的。',
        chant: 'Y, y, y. Yo-yo and yak.',
        accentColor: Color(0xFF9575CD),
      ),
      LetterSoundItem(
        letter: 'Z',
        phonicsText: '/z/',
        soundCue: 'Z says z.',
        primaryWord: 'zebra',
        secondaryWord: 'zoo',
        primaryEmoji: '🦓',
        secondaryEmoji: '🦁',
        chinesePrompt: 'Z像小蜜蜂嗡嗡飞，发声的时候喉咙会轻轻震动。',
        chant: 'Z, z, z. Zebra and zoo.',
        accentColor: Color(0xFFFFCA28),
      ),
    ],
  ),
];
