import 'package:flutter/material.dart';

import '../models/phonics_item.dart';

const List<PhonicsGroup> phonicsGroups = [
  PhonicsGroup(
    title: 'Smile Vowels',
    subtitle: 'Smile a little and make the front sounds.',
    primaryColor: Color(0xFFFFC46B),
    secondaryColor: Color(0xFFFF8A65),
    items: [
      PhonicsItem(
        symbol: '/iː/',
        title: 'Long ee',
        exampleWord: 'bee',
        examplePhrase: 'Bee, bee, a yellow bee.',
        soundCue: 'ee sound, bee',
        chinesePrompt: '这是长衣音。嘴角轻轻笑一笑，像小蜜蜂飞过来，先听 bee，再跟着说。',
        mouthTip: '嘴角向两边拉开，声音拉长一点。',
        backgroundColor: Color(0xFFFFF3E0),
      ),
      PhonicsItem(
        symbol: '/ɪ/',
        title: 'Short i',
        exampleWord: 'pig',
        examplePhrase: 'Pig, pig, a pink pig.',
        soundCue: 'i sound, pig',
        chinesePrompt: '这是短衣音。嘴巴比长衣音更放松，声音短短的，像小猪哼一下。',
        mouthTip: '嘴微微张开，声音短一点，快一点。',
        backgroundColor: Color(0xFFFFEBEE),
      ),
      PhonicsItem(
        symbol: '/e/',
        title: 'Little e',
        exampleWord: 'egg',
        examplePhrase: 'Egg, egg, an egg in the nest.',
        soundCue: 'e sound, egg',
        chinesePrompt: '这是小鹅音。像看见鸡蛋时轻轻说 eh，先听 egg，再跟读。',
        mouthTip: '嘴微张，下巴轻轻放松，不要拖长。',
        backgroundColor: Color(0xFFFFFDE7),
      ),
      PhonicsItem(
        symbol: '/æ/',
        title: 'Open a',
        exampleWord: 'cat',
        examplePhrase: 'Cat, cat, a happy cat.',
        soundCue: 'a sound, cat',
        chinesePrompt: '这是大嘴猫音。嘴巴张得更大一点，像小猫开心张嘴。',
        mouthTip: '嘴巴张开一些，声音扁扁地出来。',
        backgroundColor: Color(0xFFFCE4EC),
      ),
    ],
  ),
  PhonicsGroup(
    title: 'Middle Vowels',
    subtitle: 'Relax your mouth and let the sound roll out.',
    primaryColor: Color(0xFFA5D6A7),
    secondaryColor: Color(0xFF66BB6A),
    items: [
      PhonicsItem(
        symbol: '/ɜː/',
        title: 'Long er',
        exampleWord: 'bird',
        examplePhrase: 'Bird, bird, a bird can sing.',
        soundCue: 'er sound, bird',
        chinesePrompt: '这是长儿音。舌头放松，像小鸟慢慢唱歌，声音要稍微拉长。',
        mouthTip: '嘴巴自然张开，舌头放松，声音平稳拉长。',
        backgroundColor: Color(0xFFE8F5E9),
      ),
      PhonicsItem(
        symbol: '/ə/',
        title: 'Lazy uh',
        exampleWord: 'banana',
        examplePhrase: 'Banana is yellow and sweet.',
        soundCue: 'uh sound, banana',
        chinesePrompt: '这是轻轻的懒音。它常常藏在单词里面，轻轻带过去就可以。',
        mouthTip: '嘴巴最放松，轻轻一带，不要用力。',
        backgroundColor: Color(0xFFF1F8E9),
      ),
      PhonicsItem(
        symbol: '/ʌ/',
        title: 'Cup sound',
        exampleWord: 'sun',
        examplePhrase: 'Sun, sun, warm yellow sun.',
        soundCue: 'uh sound, sun',
        chinesePrompt: '这是太阳音。像看见太阳时轻轻啊一下，短短地说 sun。',
        mouthTip: '嘴巴自然张开，声音短而有力。',
        backgroundColor: Color(0xFFFFF8E1),
      ),
    ],
  ),
  PhonicsGroup(
    title: 'Round Vowels',
    subtitle: 'Use your round mouth for deep and warm sounds.',
    primaryColor: Color(0xFF90CAF9),
    secondaryColor: Color(0xFF42A5F5),
    items: [
      PhonicsItem(
        symbol: '/uː/',
        title: 'Long oo',
        exampleWord: 'moon',
        examplePhrase: 'Moon, moon, a bright moon.',
        soundCue: 'oo sound, moon',
        chinesePrompt: '这是长乌音。嘴巴圆圆的，像看见月亮时轻轻说 oo。',
        mouthTip: '双唇向前圆起，声音慢慢拉长。',
        backgroundColor: Color(0xFFE3F2FD),
      ),
      PhonicsItem(
        symbol: '/ʊ/',
        title: 'Short oo',
        exampleWord: 'book',
        examplePhrase: 'Book, book, open the book.',
        soundCue: 'oo sound, book',
        chinesePrompt: '这是短乌音。嘴巴也圆，但时间更短，像 quick oo。',
        mouthTip: '嘴唇微圆，声音短短地弹出来。',
        backgroundColor: Color(0xFFE1F5FE),
      ),
      PhonicsItem(
        symbol: '/ɔː/',
        title: 'Long aw',
        exampleWord: 'door',
        examplePhrase: 'Door, door, open the door.',
        soundCue: 'aw sound, door',
        chinesePrompt: '这是长喔音。像门慢慢打开时发出的喔声音。',
        mouthTip: '嘴巴圆开一点，声音向后拉长。',
        backgroundColor: Color(0xFFE8EAF6),
      ),
      PhonicsItem(
        symbol: '/ɒ/',
        title: 'Short o',
        exampleWord: 'dog',
        examplePhrase: 'Dog, dog, a funny dog.',
        soundCue: 'o sound, dog',
        chinesePrompt: '这是小狗音。像叫小狗时短短说 o，先听 dog。',
        mouthTip: '嘴巴张圆一些，声音短促有弹性。',
        backgroundColor: Color(0xFFFFF3E0),
      ),
      PhonicsItem(
        symbol: '/ɑː/',
        title: 'Long aah',
        exampleWord: 'car',
        examplePhrase: 'Car, car, a fast red car.',
        soundCue: 'aah sound, car',
        chinesePrompt: '这是长啊音。嘴巴大一点，声音从肚子里慢慢出来。',
        mouthTip: '嘴巴张大，声音长一些，放松地说。',
        backgroundColor: Color(0xFFFFEBEE),
      ),
    ],
  ),
  PhonicsGroup(
    title: 'Sliding Sounds',
    subtitle: 'Start here and slide to the next sound.',
    primaryColor: Color(0xFFCE93D8),
    secondaryColor: Color(0xFFAB47BC),
    items: [
      PhonicsItem(
        symbol: '/eɪ/',
        title: 'A slide',
        exampleWord: 'cake',
        examplePhrase: 'Cake, cake, a yummy cake.',
        soundCue: 'ay sound, cake',
        chinesePrompt: '这个音会滑一下，从 e 滑到 i，像说 ay，先听 cake。',
        mouthTip: '先微张嘴，再把嘴角轻轻拉开。',
        backgroundColor: Color(0xFFF3E5F5),
      ),
      PhonicsItem(
        symbol: '/aɪ/',
        title: 'I slide',
        exampleWord: 'kite',
        examplePhrase: 'Kite, kite, a kite in the sky.',
        soundCue: 'eye sound, kite',
        chinesePrompt: '这是爱滑音，从大嘴巴慢慢滑到小嘴巴，像 eye。',
        mouthTip: '先张开，再快速收一点，声音顺着滑过去。',
        backgroundColor: Color(0xFFEDE7F6),
      ),
      PhonicsItem(
        symbol: '/ɔɪ/',
        title: 'Toy sound',
        exampleWord: 'toy',
        examplePhrase: 'Toy, toy, my happy toy.',
        soundCue: 'oy sound, toy',
        chinesePrompt: '这是玩具音。像看见玩具时开心说 oy，先听 toy。',
        mouthTip: '嘴先圆，再往前收，声音带一点跳跃感。',
        backgroundColor: Color(0xFFE8EAF6),
      ),
      PhonicsItem(
        symbol: '/aʊ/',
        title: 'Wow sound',
        exampleWord: 'cow',
        examplePhrase: 'Cow, cow, a brown cow.',
        soundCue: 'ow sound, cow',
        chinesePrompt: '这是哇呜音，像惊喜地说 wow。先听 cow，再跟读。',
        mouthTip: '先张大嘴，再变圆嘴，声音一路滑过去。',
        backgroundColor: Color(0xFFFFF3E0),
      ),
      PhonicsItem(
        symbol: '/əʊ/',
        title: 'Go sound',
        exampleWord: 'boat',
        examplePhrase: 'Boat, boat, a boat on the lake.',
        soundCue: 'oh sound, boat',
        chinesePrompt: '这是出发音。像要出发时说 go，声音轻轻往前走。',
        mouthTip: '先放松，再把嘴唇慢慢圆起来。',
        backgroundColor: Color(0xFFE0F2F1),
      ),
      PhonicsItem(
        symbol: '/ɪə/',
        title: 'Ear sound',
        exampleWord: 'ear',
        examplePhrase: 'Ear, ear, listen with your ear.',
        soundCue: 'ear sound, ear',
        chinesePrompt: '这是耳朵音。先短短 i，再滑到轻轻的 ə。',
        mouthTip: '前面短一点，后面放松一点，慢慢滑。',
        backgroundColor: Color(0xFFE1F5FE),
      ),
      PhonicsItem(
        symbol: '/eə/',
        title: 'Air sound',
        exampleWord: 'bear',
        examplePhrase: 'Bear, bear, a soft bear.',
        soundCue: 'air sound, bear',
        chinesePrompt: '这是空气音。像摸到小熊时轻轻说 air，先听 bear。',
        mouthTip: '先 e，再轻轻放松，像在吹一口软软的气。',
        backgroundColor: Color(0xFFF1F8E9),
      ),
      PhonicsItem(
        symbol: '/ʊə/',
        title: 'Tour sound',
        exampleWord: 'tour',
        examplePhrase: 'Tour, tour, let us take a tour.',
        soundCue: 'oor sound, tour',
        chinesePrompt: '这是旅行音。先圆嘴说 ʊ，再滑到轻轻的 ə。',
        mouthTip: '嘴先圆，再慢慢放松，声音要连起来。',
        backgroundColor: Color(0xFFFFF8E1),
      ),
    ],
  ),
  PhonicsGroup(
    title: 'Brave Consonants',
    subtitle: 'Tap, pop, blow, and buzz these clear sounds.',
    primaryColor: Color(0xFFFFAB91),
    secondaryColor: Color(0xFFFF7043),
    items: [
      PhonicsItem(
        symbol: '/p/',
        title: 'Pop p',
        exampleWord: 'pig',
        examplePhrase: 'Pig plays with a pink ball.',
        soundCue: 'p sound, pig',
        chinesePrompt: '这是噗音。嘴唇先闭上，再轻轻弹开，像吹小泡泡。',
        mouthTip: '双唇闭紧，突然放开，不让声音拉长。',
        backgroundColor: Color(0xFFFFEBEE),
      ),
      PhonicsItem(
        symbol: '/t/',
        title: 'Tap t',
        exampleWord: 'ten',
        examplePhrase: 'Ten tiny toys on the table.',
        soundCue: 't sound, ten',
        chinesePrompt: '这是轻敲音。舌尖碰一下上牙后面，像轻轻敲门。',
        mouthTip: '舌尖轻碰上齿龈，马上弹开。',
        backgroundColor: Color(0xFFFFF3E0),
      ),
      PhonicsItem(
        symbol: '/k/',
        title: 'Kick k',
        exampleWord: 'kite',
        examplePhrase: 'Kite can fly in the sky.',
        soundCue: 'k sound, kite',
        chinesePrompt: '这是咔音。声音从嘴巴后面出来，像小风一下吹出。',
        mouthTip: '舌后部抬起，轻轻送气。',
        backgroundColor: Color(0xFFFFF8E1),
      ),
      PhonicsItem(
        symbol: '/b/',
        title: 'Big b',
        exampleWord: 'ball',
        examplePhrase: 'Ball bounces up and down.',
        soundCue: 'b sound, ball',
        chinesePrompt: '这是啵音。和 p 很像，但喉咙会轻轻震动。',
        mouthTip: '双唇闭合后放开，带一点嗓子震动。',
        backgroundColor: Color(0xFFFCE4EC),
      ),
      PhonicsItem(
        symbol: '/d/',
        title: 'Drum d',
        exampleWord: 'dog',
        examplePhrase: 'Dog digs in the dirt.',
        soundCue: 'd sound, dog',
        chinesePrompt: '这是咚音。舌尖碰一下，喉咙会有小小震动。',
        mouthTip: '舌尖轻碰上面，放开时带一点嗓音。',
        backgroundColor: Color(0xFFEDE7F6),
      ),
      PhonicsItem(
        symbol: '/ɡ/',
        title: 'Go g',
        exampleWord: 'goat',
        examplePhrase: 'Goat eats green grass.',
        soundCue: 'g sound, goat',
        chinesePrompt: '这是咯音。像说 go 的开头，声音从后面出来。',
        mouthTip: '舌后部抬起，放开时让嗓子震动。',
        backgroundColor: Color(0xFFE8EAF6),
      ),
      PhonicsItem(
        symbol: '/f/',
        title: 'Fan f',
        exampleWord: 'fish',
        examplePhrase: 'Fish swims in the blue sea.',
        soundCue: 'f sound, fish',
        chinesePrompt: '这是吹风音。上牙轻轻碰下唇，像吹一阵小风。',
        mouthTip: '上齿碰下唇，轻轻送气。',
        backgroundColor: Color(0xFFE1F5FE),
      ),
      PhonicsItem(
        symbol: '/v/',
        title: 'Vroom v',
        exampleWord: 'van',
        examplePhrase: 'Van moves very fast.',
        soundCue: 'v sound, van',
        chinesePrompt: '这是嗡嗡音。嘴型像 f，可是喉咙要震动。',
        mouthTip: '上齿碰下唇，同时让声音震动出来。',
        backgroundColor: Color(0xFFE0F7FA),
      ),
      PhonicsItem(
        symbol: '/s/',
        title: 'Snake s',
        exampleWord: 'sun',
        examplePhrase: 'Sun shines in the sky.',
        soundCue: 's sound, sun',
        chinesePrompt: '这是小蛇音。像小蛇嘶嘶地爬过来。',
        mouthTip: '牙齿靠近，气流从中间挤出来。',
        backgroundColor: Color(0xFFF1F8E9),
      ),
      PhonicsItem(
        symbol: '/z/',
        title: 'Bee z',
        exampleWord: 'zoo',
        examplePhrase: 'Zoo animals wave hello.',
        soundCue: 'z sound, zoo',
        chinesePrompt: '这是会震动的小蛇音。像蜜蜂在旁边嗡嗡飞。',
        mouthTip: '嘴型像 s，但加上嗓子震动。',
        backgroundColor: Color(0xFFFFFDE7),
      ),
      PhonicsItem(
        symbol: '/ʃ/',
        title: 'Shh sound',
        exampleWord: 'ship',
        examplePhrase: 'Ship sails on the sea.',
        soundCue: 'sh sound, ship',
        chinesePrompt: '这是安静音。像告诉大家 shh，小声一点。',
        mouthTip: '嘴唇微微向前，气流平稳送出。',
        backgroundColor: Color(0xFFF3E5F5),
      ),
      PhonicsItem(
        symbol: '/ʒ/',
        title: 'Zh buzz',
        exampleWord: 'vision',
        examplePhrase: 'Vision helps us see far away.',
        soundCue: 'zh sound, vision',
        chinesePrompt: '这是软软的 zh 音，像 sh 加上一点嗓子震动。',
        mouthTip: '嘴型像 sh，记得带一点震动。',
        backgroundColor: Color(0xFFEDE7F6),
      ),
      PhonicsItem(
        symbol: '/θ/',
        title: 'Thin th',
        exampleWord: 'thumb',
        examplePhrase: 'Thumb helps me hold things.',
        soundCue: 'th sound, thumb',
        chinesePrompt: '这是轻轻吐舌音。舌尖露一点点，让风轻轻出来。',
        mouthTip: '舌尖轻放在牙齿间，轻轻送气。',
        backgroundColor: Color(0xFFFFF8E1),
      ),
      PhonicsItem(
        symbol: '/ð/',
        title: 'This th',
        exampleWord: 'this',
        examplePhrase: 'This is my little toy.',
        soundCue: 'th sound, this',
        chinesePrompt: '这也是 th 音，但它会震动，像温柔地说 this。',
        mouthTip: '舌尖位置不变，加上嗓子轻轻震动。',
        backgroundColor: Color(0xFFFFF3E0),
      ),
      PhonicsItem(
        symbol: '/h/',
        title: 'Hot h',
        exampleWord: 'hat',
        examplePhrase: 'Hat is on my head.',
        soundCue: 'h sound, hat',
        chinesePrompt: '这是哈气音。像对着镜子哈一口气。',
        mouthTip: '嘴巴张开，轻轻把气呼出来。',
        backgroundColor: Color(0xFFFFEBEE),
      ),
      PhonicsItem(
        symbol: '/r/',
        title: 'Run r',
        exampleWord: 'rabbit',
        examplePhrase: 'Rabbit runs very fast.',
        soundCue: 'r sound, rabbit',
        chinesePrompt: '这是小马达音。舌头不要碰到上面，嘴巴轻轻卷一点。',
        mouthTip: '舌尖悬空，嘴唇微圆，声音向前送。',
        backgroundColor: Color(0xFFE8F5E9),
      ),
    ],
  ),
  PhonicsGroup(
    title: 'Team Sounds',
    subtitle: 'Two sounds work together like a team.',
    primaryColor: Color(0xFF80CBC4),
    secondaryColor: Color(0xFF26A69A),
    items: [
      PhonicsItem(
        symbol: '/tʃ/',
        title: 'Ch sound',
        exampleWord: 'chair',
        examplePhrase: 'Chair is near the table.',
        soundCue: 'ch sound, chair',
        chinesePrompt: '这是 ch 音。先轻轻堵住，再一下放开，像小火车出站。',
        mouthTip: '先挡住气流，再快速放开，带一点摩擦。',
        backgroundColor: Color(0xFFE0F2F1),
      ),
      PhonicsItem(
        symbol: '/tr/',
        title: 'Tr sound',
        exampleWord: 'tree',
        examplePhrase: 'Tree stands tall and green.',
        soundCue: 'tr sound, tree',
        chinesePrompt: '这是 tr 音，像小火车 tr-tr 出发。',
        mouthTip: '先有 t 的轻碰，再快速滑到 r。',
        backgroundColor: Color(0xFFE0F7FA),
      ),
      PhonicsItem(
        symbol: '/ts/',
        title: 'Ts sound',
        exampleWord: 'cats',
        examplePhrase: 'Cats jump on the sofa.',
        soundCue: 'ts sound, cats',
        chinesePrompt: '这是 ts 音。先 t，再马上带出 s，像小弹簧。',
        mouthTip: '先轻碰一下，再让气流挤出来。',
        backgroundColor: Color(0xFFE8F5E9),
      ),
      PhonicsItem(
        symbol: '/dʒ/',
        title: 'J sound',
        exampleWord: 'juice',
        examplePhrase: 'Juice is sweet and cold.',
        soundCue: 'j sound, juice',
        chinesePrompt: '这是 j 音，像果汁倒出来时轻轻说 j。',
        mouthTip: '先挡住，再放开，记得带一点震动。',
        backgroundColor: Color(0xFFFFF8E1),
      ),
      PhonicsItem(
        symbol: '/dr/',
        title: 'Dr sound',
        exampleWord: 'drum',
        examplePhrase: 'Drum goes dum dum dum.',
        soundCue: 'dr sound, drum',
        chinesePrompt: '这是 dr 音，像小鼓咚咚响。',
        mouthTip: '先 d，再顺着滑到 r，声音连起来。',
        backgroundColor: Color(0xFFFFF3E0),
      ),
      PhonicsItem(
        symbol: '/dz/',
        title: 'Dz sound',
        exampleWord: 'beds',
        examplePhrase: 'Beds are soft and warm.',
        soundCue: 'dz sound, beds',
        chinesePrompt: '这是 dz 音。像 d 和 z 手拉手，一起出来。',
        mouthTip: '先轻碰，再带着震动滑出 z。',
        backgroundColor: Color(0xFFFFEBEE),
      ),
      PhonicsItem(
        symbol: '/m/',
        title: 'Mmm sound',
        exampleWord: 'moon',
        examplePhrase: 'Moon smiles at night.',
        soundCue: 'm sound, moon',
        chinesePrompt: '这是嗯嗯音。双唇闭起来，用鼻子轻轻哼。',
        mouthTip: '双唇闭合，让声音从鼻子出来。',
        backgroundColor: Color(0xFFF3E5F5),
      ),
      PhonicsItem(
        symbol: '/n/',
        title: 'Nnn sound',
        exampleWord: 'nest',
        examplePhrase: 'Nest is in the tree.',
        soundCue: 'n sound, nest',
        chinesePrompt: '这是嗯音。舌尖碰上面，声音从鼻子出去。',
        mouthTip: '舌尖碰上齿龈，鼻子帮忙发声。',
        backgroundColor: Color(0xFFEDE7F6),
      ),
      PhonicsItem(
        symbol: '/ŋ/',
        title: 'Ng sound',
        exampleWord: 'sing',
        examplePhrase: 'Sing a happy song with me.',
        soundCue: 'ng sound, sing',
        chinesePrompt: '这是鼻尾音。像唱歌最后的 ng，要从后面收住。',
        mouthTip: '舌后部抬起，声音留在鼻腔后面。',
        backgroundColor: Color(0xFFE8EAF6),
      ),
      PhonicsItem(
        symbol: '/l/',
        title: 'Light l',
        exampleWord: 'lion',
        examplePhrase: 'Lion looks strong and brave.',
        soundCue: 'l sound, lion',
        chinesePrompt: '这是亮亮的 l 音。舌尖轻轻碰一下上面。',
        mouthTip: '舌尖碰上齿龈，声音从舌边流出来。',
        backgroundColor: Color(0xFFE1F5FE),
      ),
      PhonicsItem(
        symbol: '/j/',
        title: 'Y sound',
        exampleWord: 'yes',
        examplePhrase: 'Yes, yes, I can do it.',
        soundCue: 'y sound, yes',
        chinesePrompt: '这是 y 音，像开心答应时说 yes。',
        mouthTip: '舌头抬高一些，声音轻快地滑出来。',
        backgroundColor: Color(0xFFE8F5E9),
      ),
      PhonicsItem(
        symbol: '/w/',
        title: 'W sound',
        exampleWord: 'water',
        examplePhrase: 'Water is cool and clean.',
        soundCue: 'w sound, water',
        chinesePrompt: '这是 w 音。嘴巴先圆起来，再轻轻打开。',
        mouthTip: '先圆唇，再迅速过渡到后面的元音。',
        backgroundColor: Color(0xFFE0F7FA),
      ),
    ],
  ),
];
