import '../models/preposition_scene.dart';

const List<PrepositionScene> prepositionScenes = [
  PrepositionScene(
    title: 'in',
    chineseTitle: '在里面',
    exampleSentence: 'The ball is in the box.',
    chinesePrompt: '小球躲进盒子里，这就是 in，表示在里面。',
    playHint: 'Find the ball inside the box.',
    type: PrepositionSceneType.inBox,
  ),
  PrepositionScene(
    title: 'on',
    chineseTitle: '在上面',
    exampleSentence: 'The ball is on the box.',
    chinesePrompt: '小球放在盒子上面，这就是 on。',
    playHint: 'Tap when the ball sits on top.',
    type: PrepositionSceneType.onBox,
  ),
  PrepositionScene(
    title: 'beside',
    chineseTitle: '在旁边',
    exampleSentence: 'The ball is beside the box.',
    chinesePrompt: '小球在盒子旁边，紧紧挨着，这就是 beside。',
    playHint: 'Watch the ball stay by the box.',
    type: PrepositionSceneType.besideBox,
  ),
  PrepositionScene(
    title: 'near',
    chineseTitle: '在附近',
    exampleSentence: 'The ball is near the box.',
    chinesePrompt: '小球在盒子附近，但没有贴得那么近，这就是 near。',
    playHint: 'See the ball stop close to the box.',
    type: PrepositionSceneType.nearBox,
  ),
  PrepositionScene(
    title: 'above',
    chineseTitle: '在上方',
    exampleSentence: 'The kite is above the box.',
    chinesePrompt: '小球在盒子上方，高高的，没有碰到盒子，这就是 above。',
    playHint: 'Look up above the box.',
    type: PrepositionSceneType.aboveBox,
  ),
  PrepositionScene(
    title: 'below',
    chineseTitle: '在下方',
    exampleSentence: 'The ball is below the box.',
    chinesePrompt: '小球在盒子下方，但没有钻到正下面，这是 below。',
    playHint: 'Look below the box.',
    type: PrepositionSceneType.belowBox,
  ),
  PrepositionScene(
    title: 'over',
    chineseTitle: '在正上方',
    exampleSentence: 'The plane flies over the box.',
    chinesePrompt: '小球从盒子的正上方飞过，这就是 over。',
    playHint: 'Follow the ball over the box.',
    type: PrepositionSceneType.overBox,
  ),
  PrepositionScene(
    title: 'under',
    chineseTitle: '在正下方',
    exampleSentence: 'The cat is under the chair.',
    chinesePrompt: '小球钻到盒子的正下面，这就是 under。',
    playHint: 'See the ball hide under the box.',
    type: PrepositionSceneType.underBox,
  ),
  PrepositionScene(
    title: 'in front of',
    chineseTitle: '在前面',
    exampleSentence: 'The ball is in front of the box.',
    chinesePrompt: '小球在盒子前面，先看到小球，再看到盒子，这就是 in front of。',
    playHint: 'The ball comes to the front.',
    type: PrepositionSceneType.inFrontOfBox,
  ),
  PrepositionScene(
    title: 'behind',
    chineseTitle: '在后面',
    exampleSentence: 'The ball is behind the box.',
    chinesePrompt: '小球躲在盒子后面，这就是 behind。',
    playHint: 'The box hides the ball behind it.',
    type: PrepositionSceneType.behindBox,
  ),
  PrepositionScene(
    title: 'between',
    chineseTitle: '在中间(两者)',
    exampleSentence: 'The ball is between the boxes.',
    chinesePrompt: '小球在两个盒子中间，这就是 between。',
    playHint: 'Look for the ball in the middle.',
    type: PrepositionSceneType.betweenBoxes,
  ),
  PrepositionScene(
    title: 'among',
    chineseTitle: '在中间(多个)',
    exampleSentence: 'The ball is among the trees.',
    chinesePrompt: '小球在好多树中间，这就是 among。',
    playHint: 'Find the ball among many trees.',
    type: PrepositionSceneType.amongTrees,
  ),
  PrepositionScene(
    title: 'around',
    chineseTitle: '围绕',
    exampleSentence: 'The ball moves around the box.',
    chinesePrompt: '小球绕着盒子转圈圈，这就是 around。',
    playHint: 'Watch the ball go around and around.',
    type: PrepositionSceneType.aroundBox,
  ),
  PrepositionScene(
    title: 'from',
    chineseTitle: '从...来',
    exampleSentence: 'The bird comes from the box.',
    chinesePrompt: '小球从盒子那边过来，这就是 from。',
    playHint: 'See where the ball comes from.',
    type: PrepositionSceneType.fromBox,
  ),
  PrepositionScene(
    title: 'into',
    chineseTitle: '进入',
    exampleSentence: 'The ball goes into the box.',
    chinesePrompt: '小球往盒子里面进去，这就是 into。',
    playHint: 'Watch the ball go into the box.',
    type: PrepositionSceneType.intoBox,
  ),
  PrepositionScene(
    title: 'out of',
    chineseTitle: '从里面出来',
    exampleSentence: 'The ball comes out of the box.',
    chinesePrompt: '小球从盒子里面出来，这就是 out of。',
    playHint: 'Watch the ball come out.',
    type: PrepositionSceneType.outOfBox,
  ),
  PrepositionScene(
    title: 'onto',
    chineseTitle: '到上面去',
    exampleSentence: 'The ball jumps onto the box.',
    chinesePrompt: '小球从地上跳到盒子上面，这就是 onto。',
    playHint: 'Watch the ball jump onto the box.',
    type: PrepositionSceneType.ontoBox,
  ),
  PrepositionScene(
    title: 'off',
    chineseTitle: '离开上面',
    exampleSentence: 'The ball rolls off the box.',
    chinesePrompt: '小球从盒子上面滚下来，这就是 off。',
    playHint: 'See the ball roll off the top.',
    type: PrepositionSceneType.offBox,
  ),
  PrepositionScene(
    title: 'up',
    chineseTitle: '向上',
    exampleSentence: 'The ball goes up the hill.',
    chinesePrompt: '小球往山上走，这就是 up。',
    playHint: 'Follow the ball going up.',
    type: PrepositionSceneType.upHill,
  ),
  PrepositionScene(
    title: 'down',
    chineseTitle: '向下',
    exampleSentence: 'The ball rolls down the hill.',
    chinesePrompt: '小球往山下滚，这就是 down。',
    playHint: 'Follow the ball going down.',
    type: PrepositionSceneType.downHill,
  ),
  PrepositionScene(
    title: 'across',
    chineseTitle: '横穿',
    exampleSentence: 'The ball moves across the river.',
    chinesePrompt: '小球从这一边到那一边，横着过去，这就是 across。',
    playHint: 'Watch the ball go from side to side.',
    type: PrepositionSceneType.acrossRiver,
  ),
  PrepositionScene(
    title: 'through',
    chineseTitle: '从内部穿过',
    exampleSentence: 'The car goes through the tunnel.',
    chinesePrompt: '小球从隧道里面穿过去，这就是 through。',
    playHint: 'Look for the ball inside the tunnel.',
    type: PrepositionSceneType.throughTunnel,
  ),
];
