import '../models/preposition_scene.dart';

const List<PrepositionScene> prepositionScenes = [
  PrepositionScene(
    title: 'in',
    chineseTitle: '在里面',
    exampleSentence: 'The ball is in the box.',
    chinesePrompt: '小球在盒子里面，这就是 in。',
    playHint: '看一看：小球躲进盒子里面了。',
    type: PrepositionSceneType.inBox,
  ),
  PrepositionScene(
    title: 'on',
    chineseTitle: '在上面',
    exampleSentence: 'The ball is on the box.',
    chinesePrompt: '小球在盒子上面，这就是 on。',
    playHint: '看一看：小球正坐在盒子上面。',
    type: PrepositionSceneType.onBox,
  ),
  PrepositionScene(
    title: 'under',
    chineseTitle: '在下面',
    exampleSentence: 'The ball is under the box.',
    chinesePrompt: '小球钻到盒子下面，这就是 under。',
    playHint: '看一看：小球藏在盒子正下方。',
    type: PrepositionSceneType.underBox,
  ),
  PrepositionScene(
    title: 'behind',
    chineseTitle: '在后面',
    exampleSentence: 'The ball is behind the box.',
    chinesePrompt: '小球在盒子后面，这就是 behind。',
    playHint: '盒子把小球挡住了一部分。',
    type: PrepositionSceneType.behindBox,
  ),
  PrepositionScene(
    title: 'in front of',
    chineseTitle: '在前面',
    exampleSentence: 'The ball is in front of the box.',
    chinesePrompt: '小球在盒子前面，这就是 in front of。',
    playHint: '先看到小球，再看到后面的盒子。',
    type: PrepositionSceneType.inFrontOfBox,
  ),
  PrepositionScene(
    title: 'between',
    chineseTitle: '在中间（两个）',
    exampleSentence: 'The ball is between the boxes.',
    chinesePrompt: '小球在两个盒子中间，这就是 between。',
    playHint: '看一看：左右各有一个盒子。',
    type: PrepositionSceneType.betweenBoxes,
  ),
  PrepositionScene(
    title: 'near',
    chineseTitle: '在附近',
    exampleSentence: 'The ball is near the box.',
    chinesePrompt: '小球靠近盒子，但是没有贴上去，这就是 near。',
    playHint: '近一点，但不是挨着。',
    type: PrepositionSceneType.nearBox,
  ),
  PrepositionScene(
    title: 'above',
    chineseTitle: '在上方',
    exampleSentence: 'The ball is above the box.',
    chinesePrompt: '小球在盒子上方，没有碰到盒子，这就是 above。',
    playHint: '高高地在上面，但没有落下去。',
    type: PrepositionSceneType.aboveBox,
  ),
  PrepositionScene(
    title: 'around',
    chineseTitle: '围着',
    exampleSentence: 'The ball goes around the box.',
    chinesePrompt: '小球围着盒子转圈圈，这就是 around。',
    playHint: '注意看：小球绕着盒子一圈圈走。',
    type: PrepositionSceneType.aroundBox,
  ),
  PrepositionScene(
    title: 'into',
    chineseTitle: '进入',
    exampleSentence: 'The ball goes into the box.',
    chinesePrompt: '小球往盒子里面进去，这就是 into。',
    playHint: '先在外面，再跑进里面。',
    type: PrepositionSceneType.intoBox,
  ),
  PrepositionScene(
    title: 'out of',
    chineseTitle: '从里面出来',
    exampleSentence: 'The ball comes out of the box.',
    chinesePrompt: '小球从盒子里面出来，这就是 out of。',
    playHint: '先在里面，再出来。',
    type: PrepositionSceneType.outOfBox,
  ),
  PrepositionScene(
    title: 'through',
    chineseTitle: '穿过里面',
    exampleSentence: 'The car goes through the tunnel.',
    chinesePrompt: '小球从隧道里面穿过去，这就是 through。',
    playHint: '要从里面走过去，不是从旁边绕过去。',
    type: PrepositionSceneType.throughTunnel,
  ),
  PrepositionScene(
    title: 'across',
    chineseTitle: '横着过去',
    exampleSentence: 'The ball goes across the river.',
    chinesePrompt: '小球从这一边到那一边，这就是 across。',
    playHint: '看它从一侧移动到另一侧。',
    type: PrepositionSceneType.acrossRiver,
  ),
];
