import 'package:flutter/material.dart';

import '../models/vocabulary_item.dart';

const bodyPartsModule = VocabularyModule(
  homeTitle: 'Body',
  screenTitle: 'Body Parts',
  primaryColor: Color(0xFFFFB74D),
  secondaryColor: Color(0xFFF57C00),
  items: [
    VocabularyItem(title: 'Eye', assetPath: 'assets/images/body/Eye.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Ear', assetPath: 'assets/images/body/Ear.svg', backgroundColor: Color(0xFFE3F2FD)),
    VocabularyItem(title: 'Nose', assetPath: 'assets/images/body/Nose.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Lips', assetPath: 'assets/images/body/Lips.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Tongue', assetPath: 'assets/images/body/Tongue.svg', backgroundColor: Color(0xFFFCE4EC)),
    VocabularyItem(title: 'Teeth', assetPath: 'assets/images/body/Teeth.svg', backgroundColor: Color(0xFFF5F5F5)),
    VocabularyItem(title: 'Hair', assetPath: 'assets/images/body/Hair.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Neck', assetPath: 'assets/images/body/Neck.svg', backgroundColor: Color(0xFFEDE7F6)),
    VocabularyItem(title: 'Shoulder', assetPath: 'assets/images/body/Shoulder.svg', backgroundColor: Color(0xFFE1F5FE)),
    VocabularyItem(title: 'Arm', assetPath: 'assets/images/body/Arm.svg', backgroundColor: Color(0xFFF1F8E9)),
    VocabularyItem(title: 'Elbow', assetPath: 'assets/images/body/Elbow.svg', backgroundColor: Color(0xFFFFFDE7)),
    VocabularyItem(title: 'Palm', assetPath: 'assets/images/body/Palm.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Thumb', assetPath: 'assets/images/body/Thumb.svg', backgroundColor: Color(0xFFE8EAF6)),
    VocabularyItem(title: 'Fingers', assetPath: 'assets/images/body/Fingers.svg', backgroundColor: Color(0xFFFFF9C4)),
    VocabularyItem(title: 'Chest', assetPath: 'assets/images/body/Chest.svg', backgroundColor: Color(0xFFE0F2F1)),
    VocabularyItem(title: 'Back', assetPath: 'assets/images/body/Back.svg', backgroundColor: Color(0xFFF3E5F5)),
    VocabularyItem(title: 'Belly', assetPath: 'assets/images/body/Belly.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Stomach', assetPath: 'assets/images/body/Stomach.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Waist', assetPath: 'assets/images/body/Waist.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Hips', assetPath: 'assets/images/body/Hips.svg', backgroundColor: Color(0xFFE1F5FE)),
    VocabularyItem(title: 'Leg', assetPath: 'assets/images/body/Leg.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Knee', assetPath: 'assets/images/body/Knee.svg', backgroundColor: Color(0xFFEDE7F6)),
    VocabularyItem(title: 'Thigh', assetPath: 'assets/images/body/Thigh.svg', backgroundColor: Color(0xFFF1F8E9)),
    VocabularyItem(title: 'Foot', assetPath: 'assets/images/body/Foot.svg', backgroundColor: Color(0xFFE3F2FD)),
    VocabularyItem(title: 'Toe', assetPath: 'assets/images/body/Toe.svg', backgroundColor: Color(0xFFFFFDE7)),
    VocabularyItem(title: 'Nail', assetPath: 'assets/images/body/Nail.svg', backgroundColor: Color(0xFFF5F5F5)),
    VocabularyItem(title: 'Ankle', assetPath: 'assets/images/body/Ankle.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Cheek', assetPath: 'assets/images/body/Cheek.svg', backgroundColor: Color(0xFFFCE4EC)),
    VocabularyItem(title: 'Chin', assetPath: 'assets/images/body/Chin.svg', backgroundColor: Color(0xFFE8EAF6)),
    VocabularyItem(title: 'Wrist', assetPath: 'assets/images/body/Wrist.svg', backgroundColor: Color(0xFFE0F2F1)),
  ],
);

const fruitsAndVeggiesModule = VocabularyModule(
  homeTitle: 'Fruit\nVeggie',
  screenTitle: 'Fruits & Veggies',
  primaryColor: Color(0xFF81C784),
  secondaryColor: Color(0xFF2E7D32),
  homeFontSize: 54.0,
  homeMaxLines: 2,
  items: [
    VocabularyItem(title: 'Apple', assetPath: 'assets/images/fruits_veggies/apple.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Banana', assetPath: 'assets/images/fruits_veggies/banana.svg', backgroundColor: Color(0xFFFFFDE7)),
    VocabularyItem(title: 'Orange', assetPath: 'assets/images/fruits_veggies/orange.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Grapes', assetPath: 'assets/images/fruits_veggies/grapes.svg', backgroundColor: Color(0xFFF3E5F5)),
    VocabularyItem(title: 'Watermelon', assetPath: 'assets/images/fruits_veggies/watermelon.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Pineapple', assetPath: 'assets/images/fruits_veggies/pineapple.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Kiwi', assetPath: 'assets/images/fruits_veggies/kiwi.svg', backgroundColor: Color(0xFFF1F8E9)),
    VocabularyItem(title: 'Strawberry', assetPath: 'assets/images/fruits_veggies/strawberry.png', backgroundColor: Color(0xFFFCE4EC)),
    VocabularyItem(title: 'Carrot', assetPath: 'assets/images/fruits_veggies/carrot.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Tomato', assetPath: 'assets/images/fruits_veggies/tomato.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Potato', assetPath: 'assets/images/fruits_veggies/potato.svg', backgroundColor: Color(0xFFF5F5F5)),
    VocabularyItem(title: 'Onion', assetPath: 'assets/images/fruits_veggies/onion.png', backgroundColor: Color(0xFFEDE7F6)),
    VocabularyItem(title: 'Eggplant', assetPath: 'assets/images/fruits_veggies/eggplant.svg', backgroundColor: Color(0xFFEDE7F6)),
    VocabularyItem(title: 'Okra', assetPath: 'assets/images/fruits_veggies/okra.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Ginger', assetPath: 'assets/images/fruits_veggies/ginger.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Chilli', assetPath: 'assets/images/fruits_veggies/chilli.svg', backgroundColor: Color(0xFFFFEBEE)),
  ],
);

const flowersModule = VocabularyModule(
  homeTitle: 'Flowers',
  screenTitle: 'Flowers',
  primaryColor: Color(0xFFF48FB1),
  secondaryColor: Color(0xFFC2185B),
  homeFontSize: 62.0,
  items: [
    VocabularyItem(title: 'Rose', assetPath: 'assets/images/flowers/rose.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Sunflower', assetPath: 'assets/images/flowers/sunflower.svg', backgroundColor: Color(0xFFFFFDE7)),
    VocabularyItem(title: 'Lily', assetPath: 'assets/images/flowers/lily.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Tulip', assetPath: 'assets/images/flowers/tulip.svg', backgroundColor: Color(0xFFFCE4EC)),
    VocabularyItem(title: 'Daisy', assetPath: 'assets/images/flowers/daisy.svg', backgroundColor: Color(0xFFF5F5F5)),
    VocabularyItem(title: 'Marigold', assetPath: 'assets/images/flowers/marigold.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Lavender', assetPath: 'assets/images/flowers/lavender.svg', backgroundColor: Color(0xFFEDE7F6)),
    VocabularyItem(title: 'Hibiscus', assetPath: 'assets/images/flowers/hibiscus.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Jasmine', assetPath: 'assets/images/flowers/jasmine.svg', backgroundColor: Color(0xFFE1F5FE)),
    VocabularyItem(title: 'Lotus', assetPath: 'assets/images/flowers/lotus.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Poppy', assetPath: 'assets/images/flowers/poppy.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Daffodil', assetPath: 'assets/images/flowers/daffodil.svg', backgroundColor: Color(0xFFFFFDE7)),
  ],
);

const occupationsModule = VocabularyModule(
  homeTitle: 'Jobs',
  screenTitle: 'Jobs',
  primaryColor: Color(0xFF4FC3F7),
  secondaryColor: Color(0xFF0288D1),
  homeFontSize: 76.0,
  items: [
    VocabularyItem(title: 'Doctor', assetPath: 'assets/images/occupations/doctor.svg', backgroundColor: Color(0xFFE3F2FD)),
    VocabularyItem(title: 'Teacher', assetPath: 'assets/images/occupations/teacher.svg', backgroundColor: Color(0xFFFFF9C4)),
    VocabularyItem(title: 'Police Officer', assetPath: 'assets/images/occupations/police.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Engineer', assetPath: 'assets/images/occupations/engineer.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Pilot', assetPath: 'assets/images/occupations/pilot.svg', backgroundColor: Color(0xFFF5F5F5)),
    VocabularyItem(title: 'Artist', assetPath: 'assets/images/occupations/artist.svg', backgroundColor: Color(0xFFF3E5F5)),
    VocabularyItem(title: 'Farmer', assetPath: 'assets/images/occupations/farmer.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Vet', assetPath: 'assets/images/occupations/vet.svg', backgroundColor: Color(0xFFE0F7FA)),
    VocabularyItem(title: 'Photographer', assetPath: 'assets/images/occupations/photographer.svg', backgroundColor: Color(0xFFE1F5FE)),
    VocabularyItem(title: 'Dentist', assetPath: 'assets/images/occupations/dentist.svg', backgroundColor: Color(0xFFF5F5F5)),
    VocabularyItem(title: 'Barber', assetPath: 'assets/images/occupations/barber.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Carpenter', assetPath: 'assets/images/occupations/carpenter.svg', backgroundColor: Color(0xFFFFF8E1)),
  ],
);

const seasonsModule = VocabularyModule(
  homeTitle: 'Seasons',
  screenTitle: 'Seasons',
  primaryColor: Color(0xFFB39DDB),
  secondaryColor: Color(0xFF673AB7),
  homeFontSize: 58.0,
  items: [
    VocabularyItem(title: 'Spring', assetPath: 'assets/images/seasons/spring.svg', backgroundColor: Color(0xFFE8F5E9)),
    VocabularyItem(title: 'Summer', assetPath: 'assets/images/seasons/summer.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Autumn', assetPath: 'assets/images/seasons/autumn.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Winter', assetPath: 'assets/images/seasons/winter.svg', backgroundColor: Color(0xFFE3F2FD)),
  ],
);

const spaceModule = VocabularyModule(
  homeTitle: 'Space',
  screenTitle: 'Solar System',
  primaryColor: Color(0xFF90CAF9),
  secondaryColor: Color(0xFF283593),
  homeFontSize: 72.0,
  items: [
    VocabularyItem(title: 'Sun', assetPath: 'assets/images/solar/sun.svg', backgroundColor: Color(0xFFFFF9C4)),
    VocabularyItem(title: 'Mercury', assetPath: 'assets/images/solar/mercury.svg', backgroundColor: Color(0xFFF5F5F5)),
    VocabularyItem(title: 'Venus', assetPath: 'assets/images/solar/venus.svg', backgroundColor: Color(0xFFFFECB3)),
    VocabularyItem(title: 'Earth', assetPath: 'assets/images/solar/earth.svg', backgroundColor: Color(0xFFE3F2FD)),
    VocabularyItem(title: 'Mars', assetPath: 'assets/images/solar/mars.svg', backgroundColor: Color(0xFFFFEBEE)),
    VocabularyItem(title: 'Jupiter', assetPath: 'assets/images/solar/jupiter.svg', backgroundColor: Color(0xFFFFF3E0)),
    VocabularyItem(title: 'Saturn', assetPath: 'assets/images/solar/saturn.svg', backgroundColor: Color(0xFFFFF8E1)),
    VocabularyItem(title: 'Uranus', assetPath: 'assets/images/solar/uranus.svg', backgroundColor: Color(0xFFE1F5FE)),
    VocabularyItem(title: 'Neptune', assetPath: 'assets/images/solar/neptune.svg', backgroundColor: Color(0xFFE8EAF6)),
  ],
);
